# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p19011', '0002_my_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my',
            name='phone',
        ),
    ]
