# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='is_banner',
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='level',
            field=models.CharField(choices=[('gj', '高级'), ('zj', '中级'), ('cj', '初级')], default='cj', max_length=5, verbose_name='课程难度'),
        ),
    ]
