# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
        migrations.AddField(
            model_name='movie',
            name='daoyan',
            field=models.CharField(default=1, max_length=255, verbose_name='导演'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Daaoyan',
        ),
    ]
