# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190507_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='blog_type',
        ),
        migrations.AddField(
            model_name='movie',
            name='blog_type',
            field=models.ManyToManyField(to='movie.Biaoqian'),
        ),
    ]
