# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190507_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaoqian',
            name='biaoqian',
            field=models.CharField(max_length=8, verbose_name='电影标签'),
        ),
    ]
