# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginfo',
            name='detail',
            field=models.TextField(default=1, verbose_name='机构详情'),
            preserve_default=False,
        ),
    ]
